#https://v1.mk/13tbcYH

[custom]
;不要随意改变关键字，否则会导致出错
;自定义转换规则模版

;设置规则标志位
ruleset=Mono手动切换,https://ghproxy.net/https://raw.githubusercontent.com/Monoiscrazy/monoacl/main/sdqh.list
ruleset=DIRECT,https://ghproxy.net/https://raw.githubusercontent.com/Monoiscrazy/monoacl/main/qqzl.list
ruleset=🚀 节点选择,https://ghproxy.net/https://raw.githubusercontent.com/Monoiscrazy/monoacl/main/cmsjiedian.list
ruleset=DIRECT,https://ghproxy.net/https://raw.githubusercontent.com/Monoiscrazy/monoacl/main/cms.list
ruleset=a2h,https://ghproxy.net/https://raw.githubusercontent.com/Monoiscrazy/monoacl/main/okx.list
ruleset=Porn,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Porn.list
ruleset=Porn,https://ghproxy.net/https://raw.githubusercontent.com/Monoiscrazy/monoacl/main/porn.list
ruleset=DIRECT,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Xunlei.list
ruleset=DIRECT,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GameDownload.list
ruleset=♻️ 自动选择 GCP,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Reddit.yaml
ruleset=💬 Ai,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/AI.list
ruleset=💬 Ai,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=DIRECT,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=DIRECT,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=REJECT,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=REJECT,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=REJECT,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyList.list
ruleset=REJECT,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list
ruleset=REJECT,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyPrivacy.list
ruleset=🚀 节点选择,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🚀 节点选择,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=DIRECT,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=DIRECT,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Bing.list
ruleset=DIRECT,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/OneDrive.yaml
ruleset=DIRECT,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=DIRECT,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=a2h,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=🎮 游戏平台,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Epic.list
ruleset=🎮 游戏平台,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Origin.list
ruleset=🎮 游戏平台,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Sony.list
ruleset=🎮 游戏平台,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Steam.list
ruleset=🎮 游戏平台,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/Nintendo.list
ruleset=🎮 游戏平台,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Xbox.yaml
ruleset=📹 油管视频,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/YouTube.yaml
ruleset=🚀 节点选择,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyMedia.yaml
ruleset=🚀 节点选择,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyGFWlist.list
ruleset=DIRECT,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=DIRECT,https://ghproxy.net/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
ruleset=1panel,https://ghproxy.net/https://raw.githubusercontent.com/Monoiscrazy/monoacl/main/1panel.list
ruleset=DIRECT,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL
;设置规则标志位

;设置分组标志位
custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择 Oracle`[]🔮 负载均衡 Oracle`[]🚀 手动切换 Oracle`[]♻️ 自动选择 GCP`[]🔮 负载均衡 GCP`[]🚀 手动切换 GCP`[]♻️ 自动选择 cm`[]🔮 负载均衡 cm`[]🚀 手动切换 cm`[]DIRECT
custom_proxy_group=Mono手动切换`select`[]🚀 节点选择`[]♻️ 自动选择 Oracle`[]🔮 负载均衡 Oracle`[]🚀 手动切换 Oracle`[]♻️ 自动选择 GCP`[]🔮 负载均衡 GCP`[]🚀 手动切换 GCP`[]♻️ 自动选择 cm`[]🔮 负载均衡 cm`[]🚀 手动切换 cm
custom_proxy_group=Porn`select`[]🚀 节点选择`[]♻️ 自动选择 Oracle`[]🔮 负载均衡 Oracle`[]♻️ 自动选择 GCP`[]🔮 负载均衡 GCP`[]♻️ 自动选择 cm`[]🔮 负载均衡 cm`[]a2h`[]a3h`[]i1h`[]i2h`[]westh`[]nkh
custom_proxy_group=🚀 手动切换 Oracle`select`a2h`a3h`i1h`i2h
custom_proxy_group=🚀 手动切换 GCP`select`westh`nkh
custom_proxy_group=🚀 手动切换 cm`select`(.*CF.*|.*cf.*)
custom_proxy_group=💬 Ai`select`[]🚀 节点选择`[]♻️ 自动选择 Oracle`[]🔮 负载均衡 Oracle`[]🚀 手动切换 Oracle`[]♻️ 自动选择 GCP`[]🔮 负载均衡 GCP`[]🚀 手动切换 GCP`[]♻️ 自动选择 cm`[]🔮 负载均衡 cm`[]🚀 手动切换 cm
custom_proxy_group=📹 油管视频`select`[]🚀 节点选择`[]♻️ 自动选择 Oracle`[]🔮 负载均衡 Oracle`[]🚀 手动切换 Oracle`[]♻️ 自动选择 GCP`[]🔮 负载均衡 GCP`[]🚀 手动切换 GCP`[]♻️ 自动选择 cm`[]🔮 负载均衡 cm`[]🚀 手动切换 cm
custom_proxy_group=🎮 游戏平台`select`[]DIRECT`[]a2h`[]a3h`[]i1h`[]i2h`[]westh`[]nkh
custom_proxy_group=🐟 漏网之鱼`select`[]🚀 节点选择`[]♻️ 自动选择 Oracle`[]🔮 负载均衡 Oracle`[]🚀 手动切换 Oracle`[]♻️ 自动选择 GCP`[]🔮 负载均衡 GCP`[]🚀 手动切换 GCP`[]♻️ 自动选择 cm`[]🔮 负载均衡 cm`[]🚀 手动切换 cm`[]DIRECT
custom_proxy_group=♻️ 自动选择 Oracle`url-test`(a2h|a3h|i1h|i2h)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔮 负载均衡 Oracle`load-balance`(a2h|a3h|i1h|i2h)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=♻️ 自动选择 GCP`url-test`(westh|nkh)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔮 负载均衡 GCP`load-balance`(westh|nkh)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=♻️ 自动选择 cm`url-test`(.*CF.*|.*cf.*)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=🔮 负载均衡 cm`load-balance`(.*CF.*|.*cf.*)`http://www.gstatic.com/generate_204`300,,50
custom_proxy_group=1panel`select`[]DIRECT`[]a2h`[]a3h`[]i1h`[]i2h`[]westh`[]nkh
;设置分组标志位

enable_rule_generator=true
overwrite_original_rules=true
